#!/bin/bash
if ! command -v mdcat >/dev/null 2>&1; then echo "Install mdcat to render markdown."; fi

cat <<'EOF' | mdcat | less -R

# Byobu Commands and Tips

## Installation

- **Byobu commands (each has a manpage):

byobu, byobu-config, byobu-ctrl-a, byobu-disable, byobu-enable, byobu-export,
byobu-janitor, byobu-launch, byobu-launcher, byobu-launcher-install,
byobu-launcher-uninstall, byobu-layout, byobu-quiet, byobu-reconnect-sockets,
byobu-screen, byobu-select-backend, byobu-select-profile, byobu-select-session,
byobu-shell, byobu-silent, byobu-status, byobu-status-detail, byobu-tmux


EOF

