#!/bin/bash
if ! command -v mdcat >/dev/null 2>if ! command -v glow >/dev/null 2>&1; then echo "Install glow to render markdown."; fi1; then echo "Install mdcat to render markdown."; fi

cat <<'EOF' | mdcat | less -R
Set the shebang in a powershell script that has no .ps1 extension:

`#!/usr/bin/pwsh`
or
`#!/usr/bin/env pwsh`
If vim is not detecting the filetype in scripts without .ps1 extension:
`:set filetype=ps1`


EOF

