#!/bin/bash

if ! command -v glow >/dev/null 2>&1; then
    sudo mkdir -p /etc/apt/keyrings
    curl -fsSL https://repo.charm.sh/apt/gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/charm.gpg
    echo "deb [signed-by=/etc/apt/keyrings/charm.gpg] https://repo.charm.sh/apt/ * *" | sudo tee /etc/apt/sources.list.d/charm.list
    sudo apt update && sudo apt install glow
fi

cat <<'EOF' | glow -p

# Random important terminal tricks to remember:

- Ctrl+L, clear screen (doesn't remove anything, just pushes current prompt to top of screen). Also works in PowerShell.
- shopt -s histappend   # Allow multiple sessions to append to history at same time
- sudo !!               # Repeat last command, but with 'sudo'
- !*
- e.g. $ touch file1 file2 file3 file4
       $ chmod 777 !*                      # Repeat the arguments from the previous command
  =>   chmod 777 file1 file2 file3 file4   # Result is chmod 777 instead of touch but the same arguments

bind -p  # Show all bash bindings.
The following are some common ones:
ctrl + _ (undo)
ctrl + t (swap two characters)
alt + t (swap two words)
alt + . (prints last argument from previous command)
ctrl + x + * (expand glob/star)
ctrl + arrow (move forward a word)
alt + f (move forward a word)
alt + b (move backward a word)
ctrl + x followed by ctrl + e (opens the command string in an editor so that you can edit it before execution)
ctrl + e (move cursor to end)
ctrl + a (move cursor to start)
ctrl + xx (move to the opposite end of the line)
ctrl + u (cuts everything before the cursor)
ctrl + k (cuts everything after the cursor)
ctrl + y (pastes from the buffer)
ctrl + l (lowercase L, clears screen)

# tmux vs Windows Terminal
- Microsoft Terminal and right-click on the tab-name > Split can be as useful as tmux (though does not have the advanced features of tmux)

## 1. **Setting Up SSH Keys for Git**

### Generate SSH Key Pair
- Generate an SSH key with Ed25519 (RSA is also an option):  
  `ssh-keygen -t ed25519 -C "roysubs@hotmail.com"`
- Leave the passphrase blank for convenience, or set one for extra security.

EOF
