#!/bin/bash

cat <<'EOF' | glow -p -w $(( $(tput cols) - 6 ))
Animal ASCII Art Gallery
========================

https://www.asciiarthub.com/
https://www.asciiart.eu/
https://www.asciiart.eu/ascii-draw-studio/app

**Brighten your terminal with colorful ASCII animals!**

```plaintext
1. 🦉 Owl:
       __  
   _  (o)>  
  //\_//)   
   V_/_    

2. 🐈 Cat:
   /\_/\  
  ( o.o )  
   > ^ <  

3. 🐘 Elephant:
     /  \\~~~/  \\  
 ,----(     . .    )  
/      \\__   _    )  
\\         /         )  
 ``-----\\_______/--'  

4. 🦦 Otter:
     ()_()     
    ( o o )    
    > ^ <     

5. 🐕 Dog:
   / \__
  (    @\____
  /         O
 /   (_____/
/_____/   U  

6. 🐢 Turtle:
     _______  
   _/       \\_  
  / |       | \  
 |_/ \\_____/ \_|  
       \\ |      

7. 🐟 Fish:
      ><(((('>  

8. 🦜 Parrot:
     .--.  
   _(    )    
  / __ \\     
    (__)      

9. 🦄 Unicorn:




10. 🐁🐭🐀 Mouse:
   ()_()     
  ( o o )    
  > ^ <     

11. 🦇 Bat 
    =/\                 /\=
    / \'._   (\_/)   _.'/ \       (_                   _)
   / .''._'--(o.o)--'_.''. \       /\                 /\
  /.' _/ |`'=/ " \='`| \_ `.\     / \'._   (\_/)   _.'/ \
 /` .' `\;-,'\___/',-;/` '. '\   /_.''._'--('.')--'_.''._\
/.-' jgs   `\(-V-)/`       `-.\  | \_ / `;=/ " \=;` \ _/ |
             "   "               \/  `\__|`\___/`|__/`  \/
                                  `       \(/|\)/       `
                                           " ` "
EOF
