#!/bin/bash

cat <<'EOF' | glow -p -w $(( $(tput cols) - 6 ))
Animal ASCII Art Gallery
========================

**Brighten your terminal with colorful ASCII animals!**

```plaintext
1. 🦉 Owl:
       __  
   _  (o)>  
  //\_//)   
   V_/_    

2. 🐈 Cat:
   /\_/\  
  ( o.o )  
   > ^ <  

3. 🐘 Elephant:
     /  \\~~~/  \\  
 ,----(     . .    )  
/      \\__   _    )  
\\         /         )  
 ``-----\\_______/--'  

4. 🦦 Otter:
     ()_()     
    ( o o )    
    > ^ <     

5. 🐕 Dog:
   / \__
  (    @\____
  /         O
 /   (_____/
/_____/   U  

6. 🐢 Turtle:
     _______  
   _/       \\_  
  / |       | \  
 |_/ \\_____/ \_|  
       \\ |      

7. 🐟 Fish:
      ><(((('>  

8. 🦜 Parrot:
     .--.  
   _(    )    
  / __ \\     
    (__)      

9. 🦄 Unicorn:
            \   ^__^  
             \  (oo)\_______  
                (__)\       )\/\  
                    ||----w |  
                    ||     ||  

10. 🐀 Mouse:
   ()_()     
  ( o o )    
  > ^ <     
EOF
