#!/bin/bash

if ! command -v glow >/dev/null 2>&1; then
    sudo mkdir -p /etc/apt/keyrings
    curl -fsSL https://repo.charm.sh/apt/gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/charm.gpg
    echo "deb [signed-by=/etc/apt/keyrings/charm.gpg] https://repo.charm.sh/apt/ * *" | sudo tee /etc/apt/sources.list.d/charm.list
    sudo apt update && sudo apt install glow
fi

cat <<'EOF' | glow -p -w $(( $(tput cols) - 6 ))
# Byobu Commands and Tips

## Installation

- **Byobu commands (each has a manpage):

byobu, byobu-config, byobu-ctrl-a, byobu-disable, byobu-enable, byobu-export,
byobu-janitor, byobu-launch, byobu-launcher, byobu-launcher-install,
byobu-launcher-uninstall, byobu-layout, byobu-quiet, byobu-reconnect-sockets,
byobu-screen, byobu-select-backend, byobu-select-profile, byobu-select-session,
byobu-shell, byobu-silent, byobu-status, byobu-status-detail, byobu-tmux


EOF

