#!/bin/bash

if ! command -v mdcat >/dev/null 2>&1; then echo "Install mdcat to render markdown."; fi
WIDTH=$(if [ $(tput cols) -ge 105 ]; then echo 100; else echo $(($(tput cols) - 5)); fi)
mdcat --columns="$WIDTH" <(cat <<'EOF'


PowerShell on Linux
=====

To set the shebang for a powershell script.
```bash
#!/usr/bin/pwsh
```
```bash
#!/usr/bin/env pwsh
```
If this is set, the script does not require a `.ps1` extension.

PowerShell editing in Vim
=====
If vim is not detecting the filetype in scripts without .ps1 extension:
```bash
:set filetype=ps1
```


EOF
) | less -R
