#!/bin/bash

if ! command -v mdcat >/dev/null 2>&1; then echo "Install mdcat to render markdown."; fi
WIDTH=$(if [ $(tput cols) -ge 105 ]; then echo 100; else echo $(($(tput cols) - 5)); fi)
mdcat --columns="$WIDTH" <(cat <<EOF


# Bash `[`, `]`, and related commands cheatsheet

## Manual Pages (`man`)
- `man command`  # Show the manual page for a command

## `whatis` and `apropos`
- `whatis command`  # Display a one-line description of a command

## Tips
- Use `man -k .` to list all available commands
- Combine `man` with `less` shortcuts: `/search`, `n` (next), `N` (prev)
- Use `info command` for additional documentation
- Some commands may have `command --help` for quick reference
EOF
) | less -R
