#!/bin/bash

cat <<'EOF' | mdcat | less -R

Animal ASCII Art Gallery
========================

https://www.asciiarthub.com/
https://www.asciiart.eu/
https://www.asciiart.eu/ascii-draw-studio/app

**Brighten your terminal with colorful ASCII animals!**

```plaintext
🐔 Chicken:
       __  
   _  (o)>  
  //\_//)   
   V_/_    

🐈 Cat:
   /\_/\  
  ( o.o )  
   > ^ <  

🐁🐭🐀 Mouse:
   ()_()     
  ( o o )    
   > ^ <     


🐘 Elephant:
     /  \\~~~/  \\  
 ,----(     . .    )  
/      \\__   _    )  
\\         /         )  
 ``-----\\_______/--'  

🐕 Dog:
   / \__
  (    @\____
  /         O
 /   (_____/
/_____/   U  

🐢 Turtle:
     _______  
   _/       \\_  
  / |       | \  
 |_/ \\_____/ \_|  
       \\ |      

🐟 Fish:
      ><(((('>  

🦜 Parrot:
     .--.  
   _(    )    
  / __ \\     
    (__)      

🦇 Bat 
    =/\                 /\=
    / \'._   (\_/)   _.'/ \       (_                   _)
   / .''._'--(o.o)--'_.''. \       /\                 /\
  /.' _/ |`'=/ " \='`| \_ `.\     / \'._   (\_/)   _.'/ \
 /` .' `\;-,'\___/',-;/` '. '\   /_.''._'--('.')--'_.''._\
/.-'       `\(-V-)/`       `-.\  | \_ / `;=/ " \=;` \ _/ |
             "   "               \/  `\__|`\___/`|__/`  \/
                                  `       \(/|\)/       `
                                           " ` "
EOF
